#+title: Publishing org-mode projects on Gitlab Pages
#+author: Sachin

Example [[http://orgmode.org][org-mode]] website using [[http://pages.gitlab.io/][GitLab Pages]].

Learn more about GitLab Pages at [[https://pages.gitlab.io]] and the
official documentation [[https://docs.gitlab.com/ce/user/project/pages/]].

* Org-mode
Org-mode is [[http://www.gnu.org/philosophy/free-sw.en.html][Free Software]] and part of [[https://www.gnu.org/s/emacs/][GNU Emacs]]. It's a simple
document format ("Org") with a powerful and intuitive interface
(org-mode) that can [[http://orgmode.org/org.html#Exporting][export]] and [[http://orgmode.org/org.html#Publishing][publish]] to html, LaTeX, ascii, odt
amongst others, and [[http://orgmode.org/org.html#Working-with-source-code][evaluate source code]].

The org-mode manual can be accessed here: [[http://orgmode.org/org.html]].

The main place for Org development is the mailing list, available on
[[http://dir.gmane.org/gmane.emacs.orgmode][Gmane]].

* Gitlab CI
This project's static Pages are built by [[https://about.gitlab.com/gitlab-ci/][GitLab CI]], following the
steps defined in [[https://gitlab.com/pages/nikola/blob/master/.gitlab-ci.yml][.gitlab-ci.yml]]:

#+INCLUDE: .gitlab-ci.yml src conf

These build instructions are using a docker image, namely
~iquiw/alpine-emacs~. It makes it possible to publish the project on a
public runner on Gitlab.com.

You could probably get a better experience by using a local runner on
a server you control. If so, you can drop the ~image~ keyword.

* Building locally
Org-mode is part of GNU Emacs.  See how to obtain GNU Emacs on your OS
here: [[https://www.gnu.org/software/emacs/download.html]].

To get the latest version of Org see [[http://orgmode.org]].

* GitLab User or Group Pages
To use this project as your user/group website, you will need one
additional step: just rename your project to ~namespace.gitlab.io~,
where ~namespace~ is your ~username~ or ~groupname~. This can be done
by navigating to your project's Settings.

Read more about [[https://docs.gitlab.com/ce/user/project/pages/#user-or-group-pages][user/group Pages]] and [[https://docs.gitlab.com/ce/user/project/pages/#project-pages][project Pages]].

* TODO: How to use this repository to publish your own blogs?
